INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MANAGER_STATUS, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (1, 'admin', 'admin', '관리자', 'ADMIN', 'admin@naver.com', '010-9999-9999','Y', 'N', 'N', NULL, NULL);

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (2, 'user01', 'pass01', '김동영', 'user01', 'user01@naver.com', '010-9999-9998', 'N', 'N', NULL, NULL);

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (3, 'user02', 'pass02', '윤대한', 'user02', 'user02@naver.com', '010-9999-9997', 'N', 'N', NULL, NULL);

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (4, 'user03', 'pass03', '조동근', 'user03', 'user03@naver.com', '010-9999-9996', 'N', 'N', NULL, NULL);

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (5, 'user04', 'pass04', '박상준', 'user04', 'user04@naver.com', '010-9999-9995', 'N', 'N', NULL, NULL);

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (6, 'user05', 'pass05', '멘토1', 'Mentor1', 'mentor1@naver.com', '010-0000-0001', 'Y', 'Y', '멘토입니다1', '경력입니다1');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (7, 'user06', 'pass06', '멘토2', 'Mentor2', 'mentor2@naver.com', '010-0000-0002', 'Y', 'Y', '멘토입니다2', '경력입니다2');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (8, 'user07', 'pass07', '멘토3', 'Mentor3', 'mentor3@naver.com', '010-0000-0003', 'Y', 'Y', '멘토입니다3', '경력입니다3');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (9, 'user08', 'pass08', '멘토4', 'Mentor4', 'mentor4@naver.com', '010-0000-0004', 'Y', 'Y', '멘토입니다4', '경력입니다4');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (10, 'user09', 'pass09', '멘토5', 'Mentor5', 'mentor5@naver.com', '010-0000-0005', 'Y', 'Y', '멘토입니다5', '경력입니다5');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (11, 'user10', 'pass10', '멘토6', 'Mentor6', 'mentor6@naver.com', '010-0000-0006', 'Y', 'Y', '멘토입니다6', '경력입니다6');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (12, 'user11', 'pass11', '멘토7', 'Mentor7', 'mentor7@naver.com', '010-0000-0007', 'Y', 'Y', '멘토입니다7', '경력입니다7');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (13, 'user12', 'pass12', '멘토8', 'Mentor8', 'mentor8@naver.com', '010-0000-0008', 'Y', 'Y', '멘토입니다8', '경력입니다8');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (14, 'user13', 'pass13', '멘토9', 'Mentor9', 'mentor9@naver.com', '010-0000-0009', 'Y', 'Y', '멘토입니다9', '경력입니다9');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (15, 'user14', 'pass14', '멘토10', 'Mentor10', 'mentor10@naver.com', '010-0000-0010', 'Y', 'Y', '멘토입니다10', '경력입니다10');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (16, 'user15', 'pass15', '멘토11', 'Mentor11', 'mentor11@naver.com', '010-0000-0011', 'Y', 'Y', '멘토입니다11', '경력입니다11');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (17, 'user16', 'pass16', '멘토12', 'Mentor12', 'mentor12@naver.com', '010-0000-0012', 'Y', 'Y', '멘토입니다12', '경력입니다12');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (18, 'user17', 'pass17', '멘토13', 'Mentor13', 'mentor13@naver.com', '010-0000-0013', 'Y', 'Y', '멘토입니다13', '경력입니다13');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (19, 'user18', 'pass18', '멘토14', 'Mentor14', 'mentor14@naver.com', '010-0000-0014', 'Y', 'Y', '멘토입니다14', '경력입니다14');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (20, 'user19', 'pass19', '멘토15', 'Mentor15', 'mentor15@naver.com', '010-0000-0015', 'Y', 'Y', '멘토입니다15', '경력입니다15');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (21, 'user20', 'pass20', '멘토16', 'Mentor16', 'mentor16@naver.com', '010-0000-0016', 'Y', 'Y', '멘토입니다16', '경력입니다16');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (22, 'user21', 'pass21', '멘토17', 'Mentor17', 'mentor17@naver.com', '010-0000-0017', 'Y', 'Y', '멘토입니다17', '경력입니다17');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (23, 'user22', 'pass22', '멘토18', 'Mentor18', 'mentor18@naver.com', '010-0000-0018', 'Y', 'Y', '멘토입니다18', '경력입니다18');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (24, 'user23', 'pass23', '멘토19', 'Mentor19', 'mentor19@naver.com', '010-0000-0019', 'Y', 'Y', '멘토입니다19', '경력입니다19');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (25, 'user24', 'pass24', '멘토20', 'Mentor20', 'mentor20@naver.com', '010-0000-0020', 'Y', 'Y', '멘토입니다20', '경력입니다20');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (26, 'user25', 'pass25', '멘토21', 'Mentor21', 'mentor21@naver.com', '010-0000-0021', 'Y', 'Y', '멘토입니다21', '경력입니다21');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (27, 'user26', 'pass26', '멘토22', 'Mentor22', 'mentor22@naver.com', '010-0000-0022', 'Y', 'Y', '멘토입니다22', '경력입니다22');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (28, 'user27', 'pass27', '멘토23', 'Mentor23', 'mentor23@naver.com', '010-0000-0023', 'Y', 'Y', '멘토입니다23', '경력입니다23');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (29, 'user28', 'pass28', '멘토24', 'Mentor24', 'mentor24@naver.com', '010-0000-0024', 'Y', 'Y', '멘토입니다24', '경력입니다24');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (30, 'user29', 'pass29', '멘토25', 'Mentor25', 'mentor25@naver.com', '010-0000-0025', 'Y', 'Y', '멘토입니다25', '경력입니다25');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (31, 'user30', 'pass30', '멘토26', 'Mentor26', 'mentor26@naver.com', '010-0000-0026', 'Y', 'Y', '멘토입니다26', '경력입니다26');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (32, 'user31', 'pass31', '멘토27', 'Mentor27', 'mentor27@naver.com', '010-0000-0027', 'Y', 'Y', '멘토입니다27', '경력입니다27');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (33, 'user32', 'pass32', '멘토28', 'Mentor28', 'mentor28@naver.com', '010-0000-0028', 'Y', 'Y', '멘토입니다28', '경력입니다28');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (34, 'user33', 'pass33', '멘토29', 'Mentor29', 'mentor29@naver.com', '010-0000-0029', 'Y', 'Y', '멘토입니다29', '경력입니다29');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (35, 'user34', 'pass34', '멘토30', 'Mentor30', 'mentor30@naver.com', '010-0000-0030', 'Y', 'Y', '멘토입니다30', '경력입니다30');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (36, 'user35', 'pass35', '멘토31', 'Mentor31', 'mentor31@naver.com', '010-0000-0031', 'Y', 'Y', '멘토입니다31', '경력입니다31');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (37, 'user36', 'pass36', '멘토32', 'Mentor32', 'mentor32@naver.com', '010-0000-0032', 'Y', 'Y', '멘토입니다32', '경력입니다32');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (38, 'user37', 'pass37', '멘토33', 'Mentor33', 'mentor33@naver.com', '010-0000-0033', 'Y', 'Y', '멘토입니다33', '경력입니다33');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (39, 'user38', 'pass38', '멘토34', 'Mentor34', 'mentor34@naver.com', '010-0000-0034', 'Y', 'Y', '멘토입니다34', '경력입니다34');

