INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MANAGER_STATUS, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (1, 'admin', 'admin', '∞¸∏Æ¿⁄', 'ADMIN', 'admin@naver.com', '010-9999-9999','Y', 'N', 'N', NULL, NULL);

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (2, 'user01', 'pass01', '±Ëµøøµ', 'user01', 'user01@naver.com', '010-9999-9998', 'N', 'N', NULL, NULL);

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (3, 'user02', 'pass02', '¿±¥Î«—', 'user02', 'user02@naver.com', '010-9999-9997', 'N', 'N', NULL, NULL);

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (4, 'user03', 'pass03', '¡∂µø±Ÿ', 'user03', 'user03@naver.com', '010-9999-9996', 'N', 'N', NULL, NULL);

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (5, 'user04', 'pass04', 'π⁄ªÛ¡ÿ', 'user04', 'user04@naver.com', '010-9999-9995', 'N', 'N', NULL, NULL);

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (6, 'user05', 'pass05', '∏‡≈‰1', 'Mentor1', 'mentor1@naver.com', '010-0000-0001', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ1', '∞Ê∑¬¿‘¥œ¥Ÿ1');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (7, 'user06', 'pass06', '∏‡≈‰2', 'Mentor2', 'mentor2@naver.com', '010-0000-0002', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ2', '∞Ê∑¬¿‘¥œ¥Ÿ2');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (8, 'user07', 'pass07', '∏‡≈‰3', 'Mentor3', 'mentor3@naver.com', '010-0000-0003', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ3', '∞Ê∑¬¿‘¥œ¥Ÿ3');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (9, 'user08', 'pass08', '∏‡≈‰4', 'Mentor4', 'mentor4@naver.com', '010-0000-0004', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ4', '∞Ê∑¬¿‘¥œ¥Ÿ4');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (10, 'user09', 'pass09', '∏‡≈‰5', 'Mentor5', 'mentor5@naver.com', '010-0000-0005', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ5', '∞Ê∑¬¿‘¥œ¥Ÿ5');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (11, 'user10', 'pass10', '∏‡≈‰6', 'Mentor6', 'mentor6@naver.com', '010-0000-0006', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ6', '∞Ê∑¬¿‘¥œ¥Ÿ6');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (12, 'user11', 'pass11', '∏‡≈‰7', 'Mentor7', 'mentor7@naver.com', '010-0000-0007', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ7', '∞Ê∑¬¿‘¥œ¥Ÿ7');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (13, 'user12', 'pass12', '∏‡≈‰8', 'Mentor8', 'mentor8@naver.com', '010-0000-0008', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ8', '∞Ê∑¬¿‘¥œ¥Ÿ8');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (14, 'user13', 'pass13', '∏‡≈‰9', 'Mentor9', 'mentor9@naver.com', '010-0000-0009', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ9', '∞Ê∑¬¿‘¥œ¥Ÿ9');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (15, 'user14', 'pass14', '∏‡≈‰10', 'Mentor10', 'mentor10@naver.com', '010-0000-0010', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ10', '∞Ê∑¬¿‘¥œ¥Ÿ10');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (16, 'user15', 'pass15', '∏‡≈‰11', 'Mentor11', 'mentor11@naver.com', '010-0000-0011', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ11', '∞Ê∑¬¿‘¥œ¥Ÿ11');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (17, 'user16', 'pass16', '∏‡≈‰12', 'Mentor12', 'mentor12@naver.com', '010-0000-0012', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ12', '∞Ê∑¬¿‘¥œ¥Ÿ12');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (18, 'user17', 'pass17', '∏‡≈‰13', 'Mentor13', 'mentor13@naver.com', '010-0000-0013', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ13', '∞Ê∑¬¿‘¥œ¥Ÿ13');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (19, 'user18', 'pass18', '∏‡≈‰14', 'Mentor14', 'mentor14@naver.com', '010-0000-0014', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ14', '∞Ê∑¬¿‘¥œ¥Ÿ14');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (20, 'user19', 'pass19', '∏‡≈‰15', 'Mentor15', 'mentor15@naver.com', '010-0000-0015', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ15', '∞Ê∑¬¿‘¥œ¥Ÿ15');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (21, 'user20', 'pass20', '∏‡≈‰16', 'Mentor16', 'mentor16@naver.com', '010-0000-0016', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ16', '∞Ê∑¬¿‘¥œ¥Ÿ16');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (22, 'user21', 'pass21', '∏‡≈‰17', 'Mentor17', 'mentor17@naver.com', '010-0000-0017', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ17', '∞Ê∑¬¿‘¥œ¥Ÿ17');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (23, 'user22', 'pass22', '∏‡≈‰18', 'Mentor18', 'mentor18@naver.com', '010-0000-0018', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ18', '∞Ê∑¬¿‘¥œ¥Ÿ18');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (24, 'user23', 'pass23', '∏‡≈‰19', 'Mentor19', 'mentor19@naver.com', '010-0000-0019', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ19', '∞Ê∑¬¿‘¥œ¥Ÿ19');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (25, 'user24', 'pass24', '∏‡≈‰20', 'Mentor20', 'mentor20@naver.com', '010-0000-0020', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ20', '∞Ê∑¬¿‘¥œ¥Ÿ20');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (26, 'user25', 'pass25', '∏‡≈‰21', 'Mentor21', 'mentor21@naver.com', '010-0000-0021', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ21', '∞Ê∑¬¿‘¥œ¥Ÿ21');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (27, 'user26', 'pass26', '∏‡≈‰22', 'Mentor22', 'mentor22@naver.com', '010-0000-0022', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ22', '∞Ê∑¬¿‘¥œ¥Ÿ22');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (28, 'user27', 'pass27', '∏‡≈‰23', 'Mentor23', 'mentor23@naver.com', '010-0000-0023', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ23', '∞Ê∑¬¿‘¥œ¥Ÿ23');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (29, 'user28', 'pass28', '∏‡≈‰24', 'Mentor24', 'mentor24@naver.com', '010-0000-0024', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ24', '∞Ê∑¬¿‘¥œ¥Ÿ24');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (30, 'user29', 'pass29', '∏‡≈‰25', 'Mentor25', 'mentor25@naver.com', '010-0000-0025', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ25', '∞Ê∑¬¿‘¥œ¥Ÿ25');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (31, 'user30', 'pass30', '∏‡≈‰26', 'Mentor26', 'mentor26@naver.com', '010-0000-0026', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ26', '∞Ê∑¬¿‘¥œ¥Ÿ26');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (32, 'user31', 'pass31', '∏‡≈‰27', 'Mentor27', 'mentor27@naver.com', '010-0000-0027', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ27', '∞Ê∑¬¿‘¥œ¥Ÿ27');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (33, 'user32', 'pass32', '∏‡≈‰28', 'Mentor28', 'mentor28@naver.com', '010-0000-0028', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ28', '∞Ê∑¬¿‘¥œ¥Ÿ28');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (34, 'user33', 'pass33', '∏‡≈‰29', 'Mentor29', 'mentor29@naver.com', '010-0000-0029', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ29', '∞Ê∑¬¿‘¥œ¥Ÿ29');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (35, 'user34', 'pass34', '∏‡≈‰30', 'Mentor30', 'mentor30@naver.com', '010-0000-0030', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ30', '∞Ê∑¬¿‘¥œ¥Ÿ30');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (36, 'user35', 'pass35', '∏‡≈‰31', 'Mentor31', 'mentor31@naver.com', '010-0000-0031', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ31', '∞Ê∑¬¿‘¥œ¥Ÿ31');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (37, 'user36', 'pass36', '∏‡≈‰32', 'Mentor32', 'mentor32@naver.com', '010-0000-0032', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ32', '∞Ê∑¬¿‘¥œ¥Ÿ32');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (38, 'user37', 'pass37', '∏‡≈‰33', 'Mentor33', 'mentor33@naver.com', '010-0000-0033', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ33', '∞Ê∑¬¿‘¥œ¥Ÿ33');

INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_NICKNAME, EMAIL, PHONE, MENTOR_STATUS, MENTOR_VALID, MENTOR_INTRO, CAREER) 
VALUES (39, 'user38', 'pass38', '∏‡≈‰34', 'Mentor34', 'mentor34@naver.com', '010-0000-0034', 'Y', 'Y', '∏‡≈‰¿‘¥œ¥Ÿ34', '∞Ê∑¬¿‘¥œ¥Ÿ34');


INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (1, 1, 1, 1, '∞¯¡ˆ¿‘¥œ¥Ÿ1', '∞¯¡ˆ ≥ªøÎ¿‘¥œ¥Ÿ1', to_date('11/05/2024', 'MM/DD/RRRR'), 11, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (2, 2, 2, 3, 'æ»≥Á«œººø‰~~ 2', 'π›∞©Ω¿¥œ¥Ÿ~~ 2', to_date('11/04/2024', 'MM/DD/RRRR'), 3, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (3, 3, 3, 4, 'æ»≥Á«œººø‰~~ 3', 'π›∞©Ω¿¥œ¥Ÿ~~ 3', to_date('11/03/2024', 'MM/DD/RRRR'), 11, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (4, 4, 4, 5, 'æ»≥Á«œººø‰~~ 4', 'π›∞©Ω¿¥œ¥Ÿ~~ 4', to_date('11/02/2024', 'MM/DD/RRRR'), 15, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (5, 5, 1, 6, 'æ»≥Á«œººø‰~~ 5', 'π›∞©Ω¿¥œ¥Ÿ~~ 5', to_date('11/01/2024', 'MM/DD/RRRR'), 6, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (6, 6, 2, 7, 'æ»≥Á«œººø‰~~ 6', 'π›∞©Ω¿¥œ¥Ÿ~~ 6', to_date('10/31/2024', 'MM/DD/RRRR'), 29, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (7, 7, 3, 8, 'æ»≥Á«œººø‰~~ 7', 'π›∞©Ω¿¥œ¥Ÿ~~ 7', to_date('10/30/2024', 'MM/DD/RRRR'), 2, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (8, 2, 4, 9, 'æ»≥Á«œººø‰~~ 8', 'π›∞©Ω¿¥œ¥Ÿ~~ 8', to_date('10/29/2024', 'MM/DD/RRRR'), 0, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (9, 3, 1, 10, 'æ»≥Á«œººø‰~~ 9', 'π›∞©Ω¿¥œ¥Ÿ~~ 9', to_date('10/28/2024', 'MM/DD/RRRR'), 9, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (10, 4, 2, 11, 'æ»≥Á«œººø‰~~ 10', 'π›∞©Ω¿¥œ¥Ÿ~~ 10', to_date('10/27/2024', 'MM/DD/RRRR'), 16, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (11, 5, 3, 12, 'æ»≥Á«œººø‰~~ 11', 'π›∞©Ω¿¥œ¥Ÿ~~ 11', to_date('10/26/2024', 'MM/DD/RRRR'), 22, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (12, 6, 4, 13, 'æ»≥Á«œººø‰~~ 12', 'π›∞©Ω¿¥œ¥Ÿ~~ 12', to_date('10/25/2024', 'MM/DD/RRRR'), 14, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (13, 7, 1, 14, 'æ»≥Á«œººø‰~~ 13', 'π›∞©Ω¿¥œ¥Ÿ~~ 13', to_date('10/24/2024', 'MM/DD/RRRR'), 2, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (14, 2, 2, 15, 'æ»≥Á«œººø‰~~ 14', 'π›∞©Ω¿¥œ¥Ÿ~~ 14', to_date('10/23/2024', 'MM/DD/RRRR'), 8, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (15, 3, 3, 16, 'æ»≥Á«œººø‰~~ 15', 'π›∞©Ω¿¥œ¥Ÿ~~ 15', to_date('10/22/2024', 'MM/DD/RRRR'), 11, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (16, 4, 4, 17, 'æ»≥Á«œººø‰~~ 16', 'π›∞©Ω¿¥œ¥Ÿ~~ 16', to_date('10/21/2024', 'MM/DD/RRRR'), 12, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (17, 5, 1, 18, 'æ»≥Á«œººø‰~~ 17', 'π›∞©Ω¿¥œ¥Ÿ~~ 17', to_date('10/20/2024', 'MM/DD/RRRR'), 1, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (18, 6, 2, 19, 'æ»≥Á«œººø‰~~ 18', 'π›∞©Ω¿¥œ¥Ÿ~~ 18', to_date('10/19/2024', 'MM/DD/RRRR'), 24, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (19, 7, 3, 20, 'æ»≥Á«œººø‰~~ 19', 'π›∞©Ω¿¥œ¥Ÿ~~ 19', to_date('10/18/2024', 'MM/DD/RRRR'), 15, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (20, 2, 4, 21, 'æ»≥Á«œººø‰~~ 20', 'π›∞©Ω¿¥œ¥Ÿ~~ 20', to_date('10/17/2024', 'MM/DD/RRRR'), 22, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (21, 3, 1, 22, 'æ»≥Á«œººø‰~~ 21', 'π›∞©Ω¿¥œ¥Ÿ~~ 21', to_date('10/16/2024', 'MM/DD/RRRR'), 17, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (22, 4, 2, 23, 'æ»≥Á«œººø‰~~ 22', 'π›∞©Ω¿¥œ¥Ÿ~~ 22', to_date('10/15/2024', 'MM/DD/RRRR'), 9, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (23, 5, 3, 24, 'æ»≥Á«œººø‰~~ 23', 'π›∞©Ω¿¥œ¥Ÿ~~ 23', to_date('10/14/2024', 'MM/DD/RRRR'), 4, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (24, 6, 4, 25, 'æ»≥Á«œººø‰~~ 24', 'π›∞©Ω¿¥œ¥Ÿ~~ 24', to_date('10/13/2024', 'MM/DD/RRRR'), 6, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (25, 2, 1, 26, 'æ»≥Á«œººø‰~~ 25', 'π›∞©Ω¿¥œ¥Ÿ~~ 25', to_date('10/12/2024', 'MM/DD/RRRR'), 0, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (26, 3, 2, 27, 'æ»≥Á«œººø‰~~ 26', 'π›∞©Ω¿¥œ¥Ÿ~~ 26', to_date('10/11/2024', 'MM/DD/RRRR'), 11, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (27, 4, 3, 28, 'æ»≥Á«œººø‰~~ 27', 'π›∞©Ω¿¥œ¥Ÿ~~ 27', to_date('10/10/2024', 'MM/DD/RRRR'), 1, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (28, 5, 4, 29, 'æ»≥Á«œººø‰~~ 28', 'π›∞©Ω¿¥œ¥Ÿ~~ 28', to_date('10/09/2024', 'MM/DD/RRRR'), 20, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (29, 6, 1, 30, 'æ»≥Á«œººø‰~~ 29', 'π›∞©Ω¿¥œ¥Ÿ~~ 29', to_date('10/08/2024', 'MM/DD/RRRR'), 15, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (30, 7, 2, 31, 'æ»≥Á«œººø‰~~ 30', 'π›∞©Ω¿¥œ¥Ÿ~~ 30', to_date('10/07/2024', 'MM/DD/RRRR'), 0, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (31, 2, 3, 32, 'æ»≥Á«œººø‰~~ 31', 'π›∞©Ω¿¥œ¥Ÿ~~ 31', to_date('10/06/2024', 'MM/DD/RRRR'), 14, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (32, 3, 4, 33, 'æ»≥Á«œººø‰~~ 32', 'π›∞©Ω¿¥œ¥Ÿ~~ 32', to_date('10/05/2024', 'MM/DD/RRRR'), 4, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (33, 4, 1, 34, 'æ»≥Á«œººø‰~~ 33', 'π›∞©Ω¿¥œ¥Ÿ~~ 33', to_date('10/04/2024', 'MM/DD/RRRR'), 11, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (34, 1, 2, 1, '∞¯¡ˆ¿‘¥œ¥Ÿ2', '∞¯¡ˆ ≥ªøÎ¿‘¥œ¥Ÿ2', to_date('10/03/2024', 'MM/DD/RRRR'), 2, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (35, 6, 3, 36, 'æ»≥Á«œººø‰~~ 35', 'π›∞©Ω¿¥œ¥Ÿ~~ 35', to_date('10/02/2024', 'MM/DD/RRRR'), 10, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (36, 7, 4, 37, 'æ»≥Á«œººø‰~~ 36', 'π›∞©Ω¿¥œ¥Ÿ~~ 36', to_date('10/01/2024', 'MM/DD/RRRR'), 26, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (37, 2, 1, 38, 'æ»≥Á«œººø‰~~ 37', 'π›∞©Ω¿¥œ¥Ÿ~~ 37', to_date('09/30/2024', 'MM/DD/RRRR'), 0, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (38, 3, 2, 39, 'æ»≥Á«œººø‰~~ 38', 'π›∞©Ω¿¥œ¥Ÿ~~ 38', to_date('09/29/2024', 'MM/DD/RRRR'), 30, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (39, 4, 3, 2, 'æ»≥Á«œººø‰~~ 39', 'π›∞©Ω¿¥œ¥Ÿ~~ 39', to_date('09/28/2024', 'MM/DD/RRRR'), 0, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (40, 5, 4, 3, 'æ»≥Á«œººø‰~~ 40', 'π›∞©Ω¿¥œ¥Ÿ~~ 40', to_date('09/27/2024', 'MM/DD/RRRR'), 5, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (41, 6, 1, 4, 'æ»≥Á«œººø‰~~ 41', 'π›∞©Ω¿¥œ¥Ÿ~~ 41', to_date('09/26/2024', 'MM/DD/RRRR'), 13, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (42, 7, 2, 5, 'æ»≥Á«œººø‰~~ 42', 'π›∞©Ω¿¥œ¥Ÿ~~ 42', to_date('09/25/2024', 'MM/DD/RRRR'), 11, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (43, 2, 3, 6, 'æ»≥Á«œººø‰~~ 43', 'π›∞©Ω¿¥œ¥Ÿ~~ 43', to_date('09/24/2024', 'MM/DD/RRRR'), 6, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (44, 3, 4, 7, 'æ»≥Á«œººø‰~~ 44', 'π›∞©Ω¿¥œ¥Ÿ~~ 44', to_date('09/23/2024', 'MM/DD/RRRR'), 9, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (45, 4, 1, 8, 'æ»≥Á«œººø‰~~ 45', 'π›∞©Ω¿¥œ¥Ÿ~~ 45', to_date('09/22/2024', 'MM/DD/RRRR'), 29, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (46, 5, 2, 9, 'æ»≥Á«œººø‰~~ 46', 'π›∞©Ω¿¥œ¥Ÿ~~ 46', to_date('09/21/2024', 'MM/DD/RRRR'), 19, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (47, 6, 3, 10, 'æ»≥Á«œººø‰~~ 47', 'π›∞©Ω¿¥œ¥Ÿ~~ 47', to_date('09/20/2024', 'MM/DD/RRRR'), 5, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (48, 2, 4, 11, 'æ»≥Á«œººø‰~~ 48', 'π›∞©Ω¿¥œ¥Ÿ~~ 48', to_date('09/19/2024', 'MM/DD/RRRR'), 26, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (49, 3, 1, 12, 'æ»≥Á«œººø‰~~ 49', 'π›∞©Ω¿¥œ¥Ÿ~~ 49', to_date('09/18/2024', 'MM/DD/RRRR'), 12, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (50, 4, 2, 13, 'æ»≥Á«œººø‰~~ 50', 'π›∞©Ω¿¥œ¥Ÿ~~ 50', to_date('09/17/2024', 'MM/DD/RRRR'), 17, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (51, 5, 3, 14, 'æ»≥Á«œººø‰~~ 51', 'π›∞©Ω¿¥œ¥Ÿ~~ 51', to_date('09/16/2024', 'MM/DD/RRRR'), 13, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (52, 6, 4, 15, 'æ»≥Á«œººø‰~~ 52', 'π›∞©Ω¿¥œ¥Ÿ~~ 52', to_date('09/15/2024', 'MM/DD/RRRR'), 27, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (53, 7, 1, 16, 'æ»≥Á«œººø‰~~ 53', 'π›∞©Ω¿¥œ¥Ÿ~~ 53', to_date('09/14/2024', 'MM/DD/RRRR'), 12, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (54, 2, 2, 17, 'æ»≥Á«œººø‰~~ 54', 'π›∞©Ω¿¥œ¥Ÿ~~ 54', to_date('09/13/2024', 'MM/DD/RRRR'), 17, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (55, 3, 3, 18, 'æ»≥Á«œººø‰~~ 55', 'π›∞©Ω¿¥œ¥Ÿ~~ 55', to_date('09/12/2024', 'MM/DD/RRRR'), 12, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (56, 4, 4, 19, 'æ»≥Á«œººø‰~~ 56', 'π›∞©Ω¿¥œ¥Ÿ~~ 56', to_date('09/11/2024', 'MM/DD/RRRR'), 0, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (57, 5, 1, 20, 'æ»≥Á«œººø‰~~ 57', 'π›∞©Ω¿¥œ¥Ÿ~~ 57', to_date('09/10/2024', 'MM/DD/RRRR'), 25, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (58, 6, 2, 21, 'æ»≥Á«œººø‰~~ 58', 'π›∞©Ω¿¥œ¥Ÿ~~ 58', to_date('09/09/2024', 'MM/DD/RRRR'), 11, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (59, 7, 3, 22, 'æ»≥Á«œººø‰~~ 59', 'π›∞©Ω¿¥œ¥Ÿ~~ 59', to_date('09/08/2024', 'MM/DD/RRRR'), 9, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (60, 2, 4, 23, 'æ»≥Á«œººø‰~~ 60', 'π›∞©Ω¿¥œ¥Ÿ~~ 60', to_date('09/07/2024', 'MM/DD/RRRR'), 6, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (61, 3, 1, 24, 'æ»≥Á«œººø‰~~ 61', 'π›∞©Ω¿¥œ¥Ÿ~~ 61', to_date('09/06/2024', 'MM/DD/RRRR'), 4, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (62, 4, 2, 25, 'æ»≥Á«œººø‰~~ 62', 'π›∞©Ω¿¥œ¥Ÿ~~ 62', to_date('09/05/2024', 'MM/DD/RRRR'), 20, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (63, 5, 3, 26, 'æ»≥Á«œººø‰~~ 63', 'π›∞©Ω¿¥œ¥Ÿ~~ 63', to_date('09/04/2024', 'MM/DD/RRRR'), 8, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (64, 6, 4, 27, 'æ»≥Á«œººø‰~~ 64', 'π›∞©Ω¿¥œ¥Ÿ~~ 64', to_date('09/03/2024', 'MM/DD/RRRR'), 3, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (65, 7, 1, 28, 'æ»≥Á«œººø‰~~ 65', 'π›∞©Ω¿¥œ¥Ÿ~~ 65', to_date('09/02/2024', 'MM/DD/RRRR'), 26, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (66, 2, 2, 29, 'æ»≥Á«œººø‰~~ 66', 'π›∞©Ω¿¥œ¥Ÿ~~ 66', to_date('09/01/2024', 'MM/DD/RRRR'), 21, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (67, 3, 3, 30, 'æ»≥Á«œººø‰~~ 67', 'π›∞©Ω¿¥œ¥Ÿ~~ 67', to_date('08/31/2024', 'MM/DD/RRRR'), 13, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (68, 4, 4, 31, 'æ»≥Á«œººø‰~~ 68', 'π›∞©Ω¿¥œ¥Ÿ~~ 68', to_date('08/30/2024', 'MM/DD/RRRR'), 26, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (69, 5, 1, 32, 'æ»≥Á«œººø‰~~ 69', 'π›∞©Ω¿¥œ¥Ÿ~~ 69', to_date('08/29/2024', 'MM/DD/RRRR'), 22, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (70, 6, 2, 33, 'æ»≥Á«œººø‰~~ 70', 'π›∞©Ω¿¥œ¥Ÿ~~ 70', to_date('08/28/2024', 'MM/DD/RRRR'), 8, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (71, 2, 3, 34, 'æ»≥Á«œººø‰~~ 71', 'π›∞©Ω¿¥œ¥Ÿ~~ 71', to_date('08/27/2024', 'MM/DD/RRRR'), 25, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (72, 3, 4, 35, 'æ»≥Á«œººø‰~~ 72', 'π›∞©Ω¿¥œ¥Ÿ~~ 72', to_date('08/26/2024', 'MM/DD/RRRR'), 29, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (73, 4, 1, 36, 'æ»≥Á«œººø‰~~ 73', 'π›∞©Ω¿¥œ¥Ÿ~~ 73', to_date('08/25/2024', 'MM/DD/RRRR'), 21, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (74, 5, 2, 37, 'æ»≥Á«œººø‰~~ 74', 'π›∞©Ω¿¥œ¥Ÿ~~ 74', to_date('08/24/2024', 'MM/DD/RRRR'), 13, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (75, 6, 3, 38, 'æ»≥Á«œººø‰~~ 75', 'π›∞©Ω¿¥œ¥Ÿ~~ 75', to_date('08/23/2024', 'MM/DD/RRRR'), 24, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (76, 7, 4, 39, 'æ»≥Á«œººø‰~~ 76', 'π›∞©Ω¿¥œ¥Ÿ~~ 76', to_date('08/22/2024', 'MM/DD/RRRR'), 17, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (77, 2, 1, 2, 'æ»≥Á«œººø‰~~ 77', 'π›∞©Ω¿¥œ¥Ÿ~~ 77', to_date('08/21/2024', 'MM/DD/RRRR'), 18, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (78, 3, 2, 3, 'æ»≥Á«œººø‰~~ 78', 'π›∞©Ω¿¥œ¥Ÿ~~ 78', to_date('08/20/2024', 'MM/DD/RRRR'), 7, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (79, 4, 3, 4, 'æ»≥Á«œººø‰~~ 79', 'π›∞©Ω¿¥œ¥Ÿ~~ 79', to_date('08/19/2024', 'MM/DD/RRRR'), 20, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (80, 5, 4, 5, 'æ»≥Á«œººø‰~~ 80', 'π›∞©Ω¿¥œ¥Ÿ~~ 80', to_date('08/18/2024', 'MM/DD/RRRR'), 10, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (81, 6, 1, 6, 'æ»≥Á«œººø‰~~ 81', 'π›∞©Ω¿¥œ¥Ÿ~~ 81', to_date('08/17/2024', 'MM/DD/RRRR'), 6, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (82, 7, 2, 7, 'æ»≥Á«œººø‰~~ 82', 'π›∞©Ω¿¥œ¥Ÿ~~ 82', to_date('08/16/2024', 'MM/DD/RRRR'), 18, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (83, 2, 3, 8, 'æ»≥Á«œººø‰~~ 83', 'π›∞©Ω¿¥œ¥Ÿ~~ 83', to_date('08/15/2024', 'MM/DD/RRRR'), 26, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (84, 3, 4, 9, 'æ»≥Á«œººø‰~~ 84', 'π›∞©Ω¿¥œ¥Ÿ~~ 84', to_date('08/14/2024', 'MM/DD/RRRR'), 14, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (85, 4, 1, 10, 'æ»≥Á«œººø‰~~ 85', 'π›∞©Ω¿¥œ¥Ÿ~~ 85', to_date('08/13/2024', 'MM/DD/RRRR'), 6, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (86, 5, 2, 11, 'æ»≥Á«œººø‰~~ 86', 'π›∞©Ω¿¥œ¥Ÿ~~ 86', to_date('08/12/2024', 'MM/DD/RRRR'), 28, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (87, 6, 3, 12, 'æ»≥Á«œººø‰~~ 87', 'π›∞©Ω¿¥œ¥Ÿ~~ 87', to_date('08/11/2024', 'MM/DD/RRRR'), 9, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (88, 7, 4, 13, 'æ»≥Á«œººø‰~~ 88', 'π›∞©Ω¿¥œ¥Ÿ~~ 88', to_date('08/10/2024', 'MM/DD/RRRR'), 28, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (89, 2, 1, 14, 'æ»≥Á«œººø‰~~ 89', 'π›∞©Ω¿¥œ¥Ÿ~~ 89', to_date('08/09/2024', 'MM/DD/RRRR'), 25, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (90, 3, 2, 15, 'æ»≥Á«œººø‰~~ 90', 'π›∞©Ω¿¥œ¥Ÿ~~ 90', to_date('08/08/2024', 'MM/DD/RRRR'), 19, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (91, 4, 3, 16, 'æ»≥Á«œººø‰~~ 91', 'π›∞©Ω¿¥œ¥Ÿ~~ 91', to_date('08/07/2024', 'MM/DD/RRRR'), 10, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (92, 5, 4, 17, 'æ»≥Á«œººø‰~~ 92', 'π›∞©Ω¿¥œ¥Ÿ~~ 92', to_date('08/06/2024', 'MM/DD/RRRR'), 22, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (93, 6, 1, 18, 'æ»≥Á«œººø‰~~ 93', 'π›∞©Ω¿¥œ¥Ÿ~~ 93', to_date('08/05/2024', 'MM/DD/RRRR'), 22, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (94, 2, 2, 19, 'æ»≥Á«œººø‰~~ 94', 'π›∞©Ω¿¥œ¥Ÿ~~ 94', to_date('08/04/2024', 'MM/DD/RRRR'), 30, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (95, 3, 3, 20, 'æ»≥Á«œººø‰~~ 95', 'π›∞©Ω¿¥œ¥Ÿ~~ 95', to_date('08/03/2024', 'MM/DD/RRRR'), 5, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (96, 4, 4, 21, 'æ»≥Á«œººø‰~~ 96', 'π›∞©Ω¿¥œ¥Ÿ~~ 96', to_date('08/02/2024', 'MM/DD/RRRR'), 26, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (97, 5, 1, 22, 'æ»≥Á«œººø‰~~ 97', 'π›∞©Ω¿¥œ¥Ÿ~~ 97', to_date('08/01/2024', 'MM/DD/RRRR'), 1, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (98, 6, 2, 23, 'æ»≥Á«œººø‰~~ 98', 'π›∞©Ω¿¥œ¥Ÿ~~ 98', to_date('07/31/2024', 'MM/DD/RRRR'), 26, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (99, 7, 3, 24, 'æ»≥Á«œººø‰~~ 99', 'π›∞©Ω¿¥œ¥Ÿ~~ 99', to_date('07/30/2024', 'MM/DD/RRRR'), 22, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (100, 2, 4, 25, 'æ»≥Á«œººø‰~~ 100', 'π›∞©Ω¿¥œ¥Ÿ~~ 100', to_date('07/29/2024', 'MM/DD/RRRR'), 9, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (101, 1, 1, 1, '∞¯¡ˆ¿‘¥œ¥Ÿ3', '∞¯¡ˆ≥ªøÎ¿‘¥œ¥Ÿ3', to_date('07/28/2024', 'MM/DD/RRRR'), 25, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (102, 4, 2, 27, 'æ»≥Á«œººø‰~~ 102', 'π›∞©Ω¿¥œ¥Ÿ~~ 102', to_date('07/27/2024', 'MM/DD/RRRR'), 24, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (103, 5, 3, 28, 'æ»≥Á«œººø‰~~ 103', 'π›∞©Ω¿¥œ¥Ÿ~~ 103', to_date('07/26/2024', 'MM/DD/RRRR'), 17, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (104, 6, 4, 29, 'æ»≥Á«œººø‰~~ 104', 'π›∞©Ω¿¥œ¥Ÿ~~ 104', to_date('07/25/2024', 'MM/DD/RRRR'), 10, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (105, 7, 1, 30, 'æ»≥Á«œººø‰~~ 105', 'π›∞©Ω¿¥œ¥Ÿ~~ 105', to_date('07/24/2024', 'MM/DD/RRRR'), 4, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (106, 2, 2, 31, 'æ»≥Á«œººø‰~~ 106', 'π›∞©Ω¿¥œ¥Ÿ~~ 106', to_date('07/23/2024', 'MM/DD/RRRR'), 24, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (107, 3, 3, 32, 'æ»≥Á«œººø‰~~ 107', 'π›∞©Ω¿¥œ¥Ÿ~~ 107', to_date('07/22/2024', 'MM/DD/RRRR'), 26, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (108, 4, 4, 33, 'æ»≥Á«œººø‰~~ 108', 'π›∞©Ω¿¥œ¥Ÿ~~ 108', to_date('07/21/2024', 'MM/DD/RRRR'), 22, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (109, 5, 1, 34, 'æ»≥Á«œººø‰~~ 109', 'π›∞©Ω¿¥œ¥Ÿ~~ 109', to_date('07/20/2024', 'MM/DD/RRRR'), 26, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (110, 6, 2, 35, 'æ»≥Á«œººø‰~~ 110', 'π›∞©Ω¿¥œ¥Ÿ~~ 110', to_date('07/19/2024', 'MM/DD/RRRR'), 22, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (111, 7, 3, 36, 'æ»≥Á«œººø‰~~ 111', 'π›∞©Ω¿¥œ¥Ÿ~~ 111', to_date('07/18/2024', 'MM/DD/RRRR'), 6, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (112, 2, 4, 37, 'æ»≥Á«œººø‰~~ 112', 'π›∞©Ω¿¥œ¥Ÿ~~ 112', to_date('07/17/2024', 'MM/DD/RRRR'), 21, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (113, 3, 1, 38, 'æ»≥Á«œººø‰~~ 113', 'π›∞©Ω¿¥œ¥Ÿ~~ 113', to_date('07/16/2024', 'MM/DD/RRRR'), 20, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (114, 4, 2, 39, 'æ»≥Á«œººø‰~~ 114', 'π›∞©Ω¿¥œ¥Ÿ~~ 114', to_date('07/15/2024', 'MM/DD/RRRR'), 12, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (115, 5, 3, 2, 'æ»≥Á«œººø‰~~ 115', 'π›∞©Ω¿¥œ¥Ÿ~~ 115', to_date('07/14/2024', 'MM/DD/RRRR'), 11, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (116, 6, 4, 3, 'æ»≥Á«œººø‰~~ 116', 'π›∞©Ω¿¥œ¥Ÿ~~ 116', to_date('07/13/2024', 'MM/DD/RRRR'), 20, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (117, 2, 1, 4, 'æ»≥Á«œººø‰~~ 117', 'π›∞©Ω¿¥œ¥Ÿ~~ 117', to_date('07/12/2024', 'MM/DD/RRRR'), 10, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (118, 3, 2, 5, 'æ»≥Á«œººø‰~~ 118', 'π›∞©Ω¿¥œ¥Ÿ~~ 118', to_date('07/11/2024', 'MM/DD/RRRR'), 16, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (119, 4, 3, 6, 'æ»≥Á«œººø‰~~ 119', 'π›∞©Ω¿¥œ¥Ÿ~~ 119', to_date('07/10/2024', 'MM/DD/RRRR'), 28, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (120, 5, 4, 7, 'æ»≥Á«œººø‰~~ 120', 'π›∞©Ω¿¥œ¥Ÿ~~ 120', to_date('07/09/2024', 'MM/DD/RRRR'), 6, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (121, 6, 1, 8, 'æ»≥Á«œººø‰~~ 121', 'π›∞©Ω¿¥œ¥Ÿ~~ 121', to_date('07/08/2024', 'MM/DD/RRRR'), 14, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (122, 7, 2, 9, 'æ»≥Á«œººø‰~~ 122', 'π›∞©Ω¿¥œ¥Ÿ~~ 122', to_date('07/07/2024', 'MM/DD/RRRR'), 4, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (123, 2, 3, 10, 'æ»≥Á«œººø‰~~ 123', 'π›∞©Ω¿¥œ¥Ÿ~~ 123', to_date('07/06/2024', 'MM/DD/RRRR'), 29, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (124, 3, 4, 11, 'æ»≥Á«œººø‰~~ 124', 'π›∞©Ω¿¥œ¥Ÿ~~ 124', to_date('07/05/2024', 'MM/DD/RRRR'), 2, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (125, 4, 1, 12, 'æ»≥Á«œººø‰~~ 125', 'π›∞©Ω¿¥œ¥Ÿ~~ 125', to_date('07/04/2024', 'MM/DD/RRRR'), 14, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (126, 5, 2, 13, 'æ»≥Á«œººø‰~~ 126', 'π›∞©Ω¿¥œ¥Ÿ~~ 126', to_date('07/03/2024', 'MM/DD/RRRR'), 24, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (127, 6, 3, 14, 'æ»≥Á«œººø‰~~ 127', 'π›∞©Ω¿¥œ¥Ÿ~~ 127', to_date('07/02/2024', 'MM/DD/RRRR'), 28, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (128, 7, 4, 15, 'æ»≥Á«œººø‰~~ 128', 'π›∞©Ω¿¥œ¥Ÿ~~ 128', to_date('07/01/2024', 'MM/DD/RRRR'), 15, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (129, 2, 1, 16, 'æ»≥Á«œººø‰~~ 129', 'π›∞©Ω¿¥œ¥Ÿ~~ 129', to_date('06/30/2024', 'MM/DD/RRRR'), 25, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (130, 3, 2, 17, 'æ»≥Á«œººø‰~~ 130', 'π›∞©Ω¿¥œ¥Ÿ~~ 130', to_date('06/29/2024', 'MM/DD/RRRR'), 9, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (131, 4, 3, 18, 'æ»≥Á«œººø‰~~ 131', 'π›∞©Ω¿¥œ¥Ÿ~~ 131', to_date('06/28/2024', 'MM/DD/RRRR'), 22, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (132, 5, 4, 19, 'æ»≥Á«œººø‰~~ 132', 'π›∞©Ω¿¥œ¥Ÿ~~ 132', to_date('06/27/2024', 'MM/DD/RRRR'), 0, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (133, 6, 1, 20, 'æ»≥Á«œººø‰~~ 133', 'π›∞©Ω¿¥œ¥Ÿ~~ 133', to_date('06/26/2024', 'MM/DD/RRRR'), 23, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (134, 7, 2, 21, 'æ»≥Á«œººø‰~~ 134', 'π›∞©Ω¿¥œ¥Ÿ~~ 134', to_date('06/25/2024', 'MM/DD/RRRR'), 3, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (135, 2, 3, 22, 'æ»≥Á«œººø‰~~ 135', 'π›∞©Ω¿¥œ¥Ÿ~~ 135', to_date('06/24/2024', 'MM/DD/RRRR'), 5, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (136, 3, 4, 23, 'æ»≥Á«œººø‰~~ 136', 'π›∞©Ω¿¥œ¥Ÿ~~ 136', to_date('06/23/2024', 'MM/DD/RRRR'), 28, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (137, 4, 1, 24, 'æ»≥Á«œººø‰~~ 137', 'π›∞©Ω¿¥œ¥Ÿ~~ 137', to_date('06/22/2024', 'MM/DD/RRRR'), 6, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (138, 5, 2, 25, 'æ»≥Á«œººø‰~~ 138', 'π›∞©Ω¿¥œ¥Ÿ~~ 138', to_date('06/21/2024', 'MM/DD/RRRR'), 1, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (139, 6, 3, 26, 'æ»≥Á«œººø‰~~ 139', 'π›∞©Ω¿¥œ¥Ÿ~~ 139', to_date('06/20/2024', 'MM/DD/RRRR'), 23, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (140, 2, 4, 27, 'æ»≥Á«œººø‰~~ 140', 'π›∞©Ω¿¥œ¥Ÿ~~ 140', to_date('06/19/2024', 'MM/DD/RRRR'), 26, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (141, 3, 1, 28, 'æ»≥Á«œººø‰~~ 141', 'π›∞©Ω¿¥œ¥Ÿ~~ 141', to_date('06/18/2024', 'MM/DD/RRRR'), 27, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (142, 4, 2, 29, 'æ»≥Á«œººø‰~~ 142', 'π›∞©Ω¿¥œ¥Ÿ~~ 142', to_date('06/17/2024', 'MM/DD/RRRR'), 19, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (143, 5, 3, 30, 'æ»≥Á«œººø‰~~ 143', 'π›∞©Ω¿¥œ¥Ÿ~~ 143', to_date('06/16/2024', 'MM/DD/RRRR'), 24, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (144, 6, 4, 31, 'æ»≥Á«œººø‰~~ 144', 'π›∞©Ω¿¥œ¥Ÿ~~ 144', to_date('06/15/2024', 'MM/DD/RRRR'), 17, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (145, 7, 1, 32, 'æ»≥Á«œººø‰~~ 145', 'π›∞©Ω¿¥œ¥Ÿ~~ 145', to_date('06/14/2024', 'MM/DD/RRRR'), 26, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (146, 2, 2, 33, 'æ»≥Á«œººø‰~~ 146', 'π›∞©Ω¿¥œ¥Ÿ~~ 146', to_date('06/13/2024', 'MM/DD/RRRR'), 6, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (147, 3, 3, 34, 'æ»≥Á«œººø‰~~ 147', 'π›∞©Ω¿¥œ¥Ÿ~~ 147', to_date('06/12/2024', 'MM/DD/RRRR'), 23, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (148, 4, 4, 35, 'æ»≥Á«œººø‰~~ 148', 'π›∞©Ω¿¥œ¥Ÿ~~ 148', to_date('06/11/2024', 'MM/DD/RRRR'), 8, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (149, 5, 1, 36, 'æ»≥Á«œººø‰~~ 149', 'π›∞©Ω¿¥œ¥Ÿ~~ 149', to_date('06/10/2024', 'MM/DD/RRRR'), 15, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (150, 6, 2, 37, 'æ»≥Á«œººø‰~~ 150', 'π›∞©Ω¿¥œ¥Ÿ~~ 150', to_date('06/09/2024', 'MM/DD/RRRR'), 25, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (151, 7, 3, 38, 'æ»≥Á«œººø‰~~ 151', 'π›∞©Ω¿¥œ¥Ÿ~~ 151', to_date('06/08/2024', 'MM/DD/RRRR'), 3, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (152, 2, 4, 39, 'æ»≥Á«œººø‰~~ 152', 'π›∞©Ω¿¥œ¥Ÿ~~ 152', to_date('06/07/2024', 'MM/DD/RRRR'), 12, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (153, 3, 1, 2, 'æ»≥Á«œººø‰~~ 153', 'π›∞©Ω¿¥œ¥Ÿ~~ 153', to_date('06/06/2024', 'MM/DD/RRRR'), 11, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (154, 4, 2, 3, 'æ»≥Á«œººø‰~~ 154', 'π›∞©Ω¿¥œ¥Ÿ~~ 154', to_date('06/05/2024', 'MM/DD/RRRR'), 2, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (155, 5, 3, 4, 'æ»≥Á«œººø‰~~ 155', 'π›∞©Ω¿¥œ¥Ÿ~~ 155', to_date('06/04/2024', 'MM/DD/RRRR'), 10, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (156, 6, 4, 5, 'æ»≥Á«œººø‰~~ 156', 'π›∞©Ω¿¥œ¥Ÿ~~ 156', to_date('06/03/2024', 'MM/DD/RRRR'), 14, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (157, 7, 1, 6, 'æ»≥Á«œººø‰~~ 157', 'π›∞©Ω¿¥œ¥Ÿ~~ 157', to_date('06/02/2024', 'MM/DD/RRRR'), 0, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (158, 2, 2, 7, 'æ»≥Á«œººø‰~~ 158', 'π›∞©Ω¿¥œ¥Ÿ~~ 158', to_date('06/01/2024', 'MM/DD/RRRR'), 16, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (159, 3, 3, 8, 'æ»≥Á«œººø‰~~ 159', 'π›∞©Ω¿¥œ¥Ÿ~~ 159', to_date('05/31/2024', 'MM/DD/RRRR'), 8, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (160, 4, 4, 9, 'æ»≥Á«œººø‰~~ 160', 'π›∞©Ω¿¥œ¥Ÿ~~ 160', to_date('05/30/2024', 'MM/DD/RRRR'), 23, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (161, 5, 1, 10, 'æ»≥Á«œººø‰~~ 161', 'π›∞©Ω¿¥œ¥Ÿ~~ 161', to_date('05/29/2024', 'MM/DD/RRRR'), 27, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (162, 6, 2, 11, 'æ»≥Á«œººø‰~~ 162', 'π›∞©Ω¿¥œ¥Ÿ~~ 162', to_date('05/28/2024', 'MM/DD/RRRR'), 5, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (163, 2, 3, 12, 'æ»≥Á«œººø‰~~ 163', 'π›∞©Ω¿¥œ¥Ÿ~~ 163', to_date('05/27/2024', 'MM/DD/RRRR'), 18, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (164, 3, 4, 13, 'æ»≥Á«œººø‰~~ 164', 'π›∞©Ω¿¥œ¥Ÿ~~ 164', to_date('05/26/2024', 'MM/DD/RRRR'), 14, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (165, 4, 1, 14, 'æ»≥Á«œººø‰~~ 165', 'π›∞©Ω¿¥œ¥Ÿ~~ 165', to_date('05/25/2024', 'MM/DD/RRRR'), 11, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (166, 5, 2, 15, 'æ»≥Á«œººø‰~~ 166', 'π›∞©Ω¿¥œ¥Ÿ~~ 166', to_date('05/24/2024', 'MM/DD/RRRR'), 12, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (167, 6, 3, 16, 'æ»≥Á«œººø‰~~ 167', 'π›∞©Ω¿¥œ¥Ÿ~~ 167', to_date('05/23/2024', 'MM/DD/RRRR'), 24, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (168, 7, 4, 17, 'æ»≥Á«œººø‰~~ 168', 'π›∞©Ω¿¥œ¥Ÿ~~ 168', to_date('05/22/2024', 'MM/DD/RRRR'), 11, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (169, 2, 1, 18, 'æ»≥Á«œººø‰~~ 169', 'π›∞©Ω¿¥œ¥Ÿ~~ 169', to_date('05/21/2024', 'MM/DD/RRRR'), 7, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (170, 3, 2, 19, 'æ»≥Á«œººø‰~~ 170', 'π›∞©Ω¿¥œ¥Ÿ~~ 170', to_date('05/20/2024', 'MM/DD/RRRR'), 22, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (171, 4, 3, 20, 'æ»≥Á«œººø‰~~ 171', 'π›∞©Ω¿¥œ¥Ÿ~~ 171', to_date('05/19/2024', 'MM/DD/RRRR'), 13, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (172, 5, 4, 21, 'æ»≥Á«œººø‰~~ 172', 'π›∞©Ω¿¥œ¥Ÿ~~ 172', to_date('05/18/2024', 'MM/DD/RRRR'), 16, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (173, 6, 1, 22, 'æ»≥Á«œººø‰~~ 173', 'π›∞©Ω¿¥œ¥Ÿ~~ 173', to_date('05/17/2024', 'MM/DD/RRRR'), 13, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (174, 7, 2, 23, 'æ»≥Á«œººø‰~~ 174', 'π›∞©Ω¿¥œ¥Ÿ~~ 174', to_date('05/16/2024', 'MM/DD/RRRR'), 19, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (175, 2, 3, 24, 'æ»≥Á«œººø‰~~ 175', 'π›∞©Ω¿¥œ¥Ÿ~~ 175', to_date('05/15/2024', 'MM/DD/RRRR'), 1, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (176, 3, 4, 25, 'æ»≥Á«œººø‰~~ 176', 'π›∞©Ω¿¥œ¥Ÿ~~ 176', to_date('05/14/2024', 'MM/DD/RRRR'), 2, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (177, 4, 1, 26, 'æ»≥Á«œººø‰~~ 177', 'π›∞©Ω¿¥œ¥Ÿ~~ 177', to_date('05/13/2024', 'MM/DD/RRRR'), 23, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (178, 5, 2, 27, 'æ»≥Á«œººø‰~~ 178', 'π›∞©Ω¿¥œ¥Ÿ~~ 178', to_date('05/12/2024', 'MM/DD/RRRR'), 4, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (179, 6, 3, 28, 'æ»≥Á«œººø‰~~ 179', 'π›∞©Ω¿¥œ¥Ÿ~~ 179', to_date('05/11/2024', 'MM/DD/RRRR'), 16, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (180, 7, 4, 29, 'æ»≥Á«œººø‰~~ 180', 'π›∞©Ω¿¥œ¥Ÿ~~ 180', to_date('05/10/2024', 'MM/DD/RRRR'), 15, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (181, 2, 1, 30, 'æ»≥Á«œººø‰~~ 181', 'π›∞©Ω¿¥œ¥Ÿ~~ 181', to_date('05/09/2024', 'MM/DD/RRRR'), 13, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (182, 3, 2, 31, 'æ»≥Á«œººø‰~~ 182', 'π›∞©Ω¿¥œ¥Ÿ~~ 182', to_date('05/08/2024', 'MM/DD/RRRR'), 14, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (183, 4, 3, 32, 'æ»≥Á«œººø‰~~ 183', 'π›∞©Ω¿¥œ¥Ÿ~~ 183', to_date('05/07/2024', 'MM/DD/RRRR'), 4, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (184, 5, 4, 33, 'æ»≥Á«œººø‰~~ 184', 'π›∞©Ω¿¥œ¥Ÿ~~ 184', to_date('05/06/2024', 'MM/DD/RRRR'), 20, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (185, 6, 1, 34, 'æ»≥Á«œººø‰~~ 185', 'π›∞©Ω¿¥œ¥Ÿ~~ 185', to_date('05/05/2024', 'MM/DD/RRRR'), 14, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (186, 2, 2, 35, 'æ»≥Á«œººø‰~~ 186', 'π›∞©Ω¿¥œ¥Ÿ~~ 186', to_date('05/04/2024', 'MM/DD/RRRR'), 29, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (187, 3, 3, 36, 'æ»≥Á«œººø‰~~ 187', 'π›∞©Ω¿¥œ¥Ÿ~~ 187', to_date('05/03/2024', 'MM/DD/RRRR'), 21, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (188, 4, 4, 37, 'æ»≥Á«œººø‰~~ 188', 'π›∞©Ω¿¥œ¥Ÿ~~ 188', to_date('05/02/2024', 'MM/DD/RRRR'), 5, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (189, 5, 1, 38, 'æ»≥Á«œººø‰~~ 189', 'π›∞©Ω¿¥œ¥Ÿ~~ 189', to_date('05/01/2024', 'MM/DD/RRRR'), 21, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (190, 6, 2, 39, 'æ»≥Á«œººø‰~~ 190', 'π›∞©Ω¿¥œ¥Ÿ~~ 190', to_date('04/30/2024', 'MM/DD/RRRR'), 27, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (191, 7, 3, 2, 'æ»≥Á«œººø‰~~ 191', 'π›∞©Ω¿¥œ¥Ÿ~~ 191', to_date('04/29/2024', 'MM/DD/RRRR'), 13, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (192, 2, 4, 3, 'æ»≥Á«œººø‰~~ 192', 'π›∞©Ω¿¥œ¥Ÿ~~ 192', to_date('04/28/2024', 'MM/DD/RRRR'), 26, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (193, 3, 1, 4, 'æ»≥Á«œººø‰~~ 193', 'π›∞©Ω¿¥œ¥Ÿ~~ 193', to_date('04/27/2024', 'MM/DD/RRRR'), 9, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (194, 4, 2, 5, 'æ»≥Á«œººø‰~~ 194', 'π›∞©Ω¿¥œ¥Ÿ~~ 194', to_date('04/26/2024', 'MM/DD/RRRR'), 0, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (195, 5, 3, 6, 'æ»≥Á«œººø‰~~ 195', 'π›∞©Ω¿¥œ¥Ÿ~~ 195', to_date('04/25/2024', 'MM/DD/RRRR'), 28, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (196, 6, 4, 7, 'æ»≥Á«œººø‰~~ 196', 'π›∞©Ω¿¥œ¥Ÿ~~ 196', to_date('04/24/2024', 'MM/DD/RRRR'), 10, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (197, 7, 1, 8, 'æ»≥Á«œººø‰~~ 197', 'π›∞©Ω¿¥œ¥Ÿ~~ 197', to_date('04/23/2024', 'MM/DD/RRRR'), 8, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (198, 2, 2, 9, 'æ»≥Á«œººø‰~~ 198', 'π›∞©Ω¿¥œ¥Ÿ~~ 198', to_date('04/22/2024', 'MM/DD/RRRR'), 15, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (199, 3, 3, 10, 'æ»≥Á«œººø‰~~ 199', 'π›∞©Ω¿¥œ¥Ÿ~~ 199', to_date('04/21/2024', 'MM/DD/RRRR'), 15, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (200, 4, 4, 11, 'æ»≥Á«œººø‰~~ 200', 'π›∞©Ω¿¥œ¥Ÿ~~ 200', to_date('04/20/2024', 'MM/DD/RRRR'), 13, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (201, 5, 1, 12, 'æ»≥Á«œººø‰~~ 201', 'π›∞©Ω¿¥œ¥Ÿ~~ 201', to_date('04/19/2024', 'MM/DD/RRRR'), 16, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (202, 6, 2, 13, 'æ»≥Á«œººø‰~~ 202', 'π›∞©Ω¿¥œ¥Ÿ~~ 202', to_date('04/18/2024', 'MM/DD/RRRR'), 11, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (203, 7, 3, 14, 'æ»≥Á«œººø‰~~ 203', 'π›∞©Ω¿¥œ¥Ÿ~~ 203', to_date('04/17/2024', 'MM/DD/RRRR'), 1, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (204, 2, 4, 15, 'æ»≥Á«œººø‰~~ 204', 'π›∞©Ω¿¥œ¥Ÿ~~ 204', to_date('04/16/2024', 'MM/DD/RRRR'), 29, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (205, 3, 1, 16, 'æ»≥Á«œººø‰~~ 205', 'π›∞©Ω¿¥œ¥Ÿ~~ 205', to_date('04/15/2024', 'MM/DD/RRRR'), 16, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (206, 4, 2, 17, 'æ»≥Á«œººø‰~~ 206', 'π›∞©Ω¿¥œ¥Ÿ~~ 206', to_date('04/14/2024', 'MM/DD/RRRR'), 6, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (207, 5, 3, 18, 'æ»≥Á«œººø‰~~ 207', 'π›∞©Ω¿¥œ¥Ÿ~~ 207', to_date('04/13/2024', 'MM/DD/RRRR'), 14, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (208, 6, 4, 19, 'æ»≥Á«œººø‰~~ 208', 'π›∞©Ω¿¥œ¥Ÿ~~ 208', to_date('04/12/2024', 'MM/DD/RRRR'), 10, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (209, 2, 1, 20, 'æ»≥Á«œººø‰~~ 209', 'π›∞©Ω¿¥œ¥Ÿ~~ 209', to_date('04/11/2024', 'MM/DD/RRRR'), 24, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (210, 3, 2, 21, 'æ»≥Á«œººø‰~~ 210', 'π›∞©Ω¿¥œ¥Ÿ~~ 210', to_date('04/10/2024', 'MM/DD/RRRR'), 0, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (211, 4, 3, 22, 'æ»≥Á«œººø‰~~ 211', 'π›∞©Ω¿¥œ¥Ÿ~~ 211', to_date('04/09/2024', 'MM/DD/RRRR'), 10, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (212, 5, 4, 23, 'æ»≥Á«œººø‰~~ 212', 'π›∞©Ω¿¥œ¥Ÿ~~ 212', to_date('04/08/2024', 'MM/DD/RRRR'), 10, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (213, 6, 1, 24, 'æ»≥Á«œººø‰~~ 213', 'π›∞©Ω¿¥œ¥Ÿ~~ 213', to_date('04/07/2024', 'MM/DD/RRRR'), 22, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (214, 7, 2, 25, 'æ»≥Á«œººø‰~~ 214', 'π›∞©Ω¿¥œ¥Ÿ~~ 214', to_date('04/06/2024', 'MM/DD/RRRR'), 27, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (215, 2, 3, 26, 'æ»≥Á«œººø‰~~ 215', 'π›∞©Ω¿¥œ¥Ÿ~~ 215', to_date('04/05/2024', 'MM/DD/RRRR'), 2, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (216, 3, 4, 27, 'æ»≥Á«œººø‰~~ 216', 'π›∞©Ω¿¥œ¥Ÿ~~ 216', to_date('04/04/2024', 'MM/DD/RRRR'), 12, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (217, 4, 1, 28, 'æ»≥Á«œººø‰~~ 217', 'π›∞©Ω¿¥œ¥Ÿ~~ 217', to_date('04/03/2024', 'MM/DD/RRRR'), 23, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (218, 5, 2, 29, 'æ»≥Á«œººø‰~~ 218', 'π›∞©Ω¿¥œ¥Ÿ~~ 218', to_date('04/02/2024', 'MM/DD/RRRR'), 18, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (219, 6, 3, 30, 'æ»≥Á«œººø‰~~ 219', 'π›∞©Ω¿¥œ¥Ÿ~~ 219', to_date('04/01/2024', 'MM/DD/RRRR'), 26, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (220, 7, 4, 31, 'æ»≥Á«œººø‰~~ 220', 'π›∞©Ω¿¥œ¥Ÿ~~ 220', to_date('03/31/2024', 'MM/DD/RRRR'), 25, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (221, 2, 1, 32, 'æ»≥Á«œººø‰~~ 221', 'π›∞©Ω¿¥œ¥Ÿ~~ 221', to_date('03/30/2024', 'MM/DD/RRRR'), 8, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (222, 3, 2, 33, 'æ»≥Á«œººø‰~~ 222', 'π›∞©Ω¿¥œ¥Ÿ~~ 222', to_date('03/29/2024', 'MM/DD/RRRR'), 16, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (223, 4, 3, 34, 'æ»≥Á«œººø‰~~ 223', 'π›∞©Ω¿¥œ¥Ÿ~~ 223', to_date('03/28/2024', 'MM/DD/RRRR'), 21, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (224, 5, 4, 35, 'æ»≥Á«œººø‰~~ 224', 'π›∞©Ω¿¥œ¥Ÿ~~ 224', to_date('03/27/2024', 'MM/DD/RRRR'), 4, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (225, 6, 1, 36, 'æ»≥Á«œººø‰~~ 225', 'π›∞©Ω¿¥œ¥Ÿ~~ 225', to_date('03/26/2024', 'MM/DD/RRRR'), 28, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (226, 7, 2, 37, 'æ»≥Á«œººø‰~~ 226', 'π›∞©Ω¿¥œ¥Ÿ~~ 226', to_date('03/25/2024', 'MM/DD/RRRR'), 9, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (227, 2, 3, 38, 'æ»≥Á«œººø‰~~ 227', 'π›∞©Ω¿¥œ¥Ÿ~~ 227', to_date('03/24/2024', 'MM/DD/RRRR'), 26, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (228, 3, 4, 39, 'æ»≥Á«œººø‰~~ 228', 'π›∞©Ω¿¥œ¥Ÿ~~ 228', to_date('03/23/2024', 'MM/DD/RRRR'), 29, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (229, 4, 1, 2, 'æ»≥Á«œººø‰~~ 229', 'π›∞©Ω¿¥œ¥Ÿ~~ 229', to_date('03/22/2024', 'MM/DD/RRRR'), 23, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (230, 5, 2, 3, 'æ»≥Á«œººø‰~~ 230', 'π›∞©Ω¿¥œ¥Ÿ~~ 230', to_date('03/21/2024', 'MM/DD/RRRR'), 18, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (231, 6, 3, 4, 'æ»≥Á«œººø‰~~ 231', 'π›∞©Ω¿¥œ¥Ÿ~~ 231', to_date('03/20/2024', 'MM/DD/RRRR'), 11, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (232, 2, 4, 5, 'æ»≥Á«œººø‰~~ 232', 'π›∞©Ω¿¥œ¥Ÿ~~ 232', to_date('03/19/2024', 'MM/DD/RRRR'), 14, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (233, 3, 1, 6, 'æ»≥Á«œººø‰~~ 233', 'π›∞©Ω¿¥œ¥Ÿ~~ 233', to_date('03/18/2024', 'MM/DD/RRRR'), 24, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (234, 4, 2, 7, 'æ»≥Á«œººø‰~~ 234', 'π›∞©Ω¿¥œ¥Ÿ~~ 234', to_date('03/17/2024', 'MM/DD/RRRR'), 9, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (235, 5, 3, 8, 'æ»≥Á«œººø‰~~ 235', 'π›∞©Ω¿¥œ¥Ÿ~~ 235', to_date('03/16/2024', 'MM/DD/RRRR'), 14, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (236, 6, 4, 9, 'æ»≥Á«œººø‰~~ 236', 'π›∞©Ω¿¥œ¥Ÿ~~ 236', to_date('03/15/2024', 'MM/DD/RRRR'), 11, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (237, 7, 1, 10, 'æ»≥Á«œººø‰~~ 237', 'π›∞©Ω¿¥œ¥Ÿ~~ 237', to_date('03/14/2024', 'MM/DD/RRRR'), 9, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (238, 2, 2, 11, 'æ»≥Á«œººø‰~~ 238', 'π›∞©Ω¿¥œ¥Ÿ~~ 238', to_date('03/13/2024', 'MM/DD/RRRR'), 30, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (239, 3, 3, 12, 'æ»≥Á«œººø‰~~ 239', 'π›∞©Ω¿¥œ¥Ÿ~~ 239', to_date('03/12/2024', 'MM/DD/RRRR'), 14, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (240, 4, 4, 13, 'æ»≥Á«œººø‰~~ 240', 'π›∞©Ω¿¥œ¥Ÿ~~ 240', to_date('03/11/2024', 'MM/DD/RRRR'), 27, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (241, 5, 1, 14, 'æ»≥Á«œººø‰~~ 241', 'π›∞©Ω¿¥œ¥Ÿ~~ 241', to_date('03/10/2024', 'MM/DD/RRRR'), 23, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (242, 6, 2, 15, 'æ»≥Á«œººø‰~~ 242', 'π›∞©Ω¿¥œ¥Ÿ~~ 242', to_date('03/09/2024', 'MM/DD/RRRR'), 14, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (243, 7, 3, 16, 'æ»≥Á«œººø‰~~ 243', 'π›∞©Ω¿¥œ¥Ÿ~~ 243', to_date('03/08/2024', 'MM/DD/RRRR'), 1, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (244, 2, 4, 17, 'æ»≥Á«œººø‰~~ 244', 'π›∞©Ω¿¥œ¥Ÿ~~ 244', to_date('03/07/2024', 'MM/DD/RRRR'), 11, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (245, 3, 1, 18, 'æ»≥Á«œººø‰~~ 245', 'π›∞©Ω¿¥œ¥Ÿ~~ 245', to_date('03/06/2024', 'MM/DD/RRRR'), 30, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (246, 4, 2, 19, 'æ»≥Á«œººø‰~~ 246', 'π›∞©Ω¿¥œ¥Ÿ~~ 246', to_date('03/05/2024', 'MM/DD/RRRR'), 17, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (247, 5, 3, 20, 'æ»≥Á«œººø‰~~ 247', 'π›∞©Ω¿¥œ¥Ÿ~~ 247', to_date('03/04/2024', 'MM/DD/RRRR'), 15, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (248, 6, 4, 21, 'æ»≥Á«œººø‰~~ 248', 'π›∞©Ω¿¥œ¥Ÿ~~ 248', to_date('03/03/2024', 'MM/DD/RRRR'), 24, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (249, 7, 1, 22, 'æ»≥Á«œººø‰~~ 249', 'π›∞©Ω¿¥œ¥Ÿ~~ 249', to_date('03/02/2024', 'MM/DD/RRRR'), 21, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (250, 2, 2, 23, 'æ»≥Á«œººø‰~~ 250', 'π›∞©Ω¿¥œ¥Ÿ~~ 250', to_date('03/01/2024', 'MM/DD/RRRR'), 11, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (251, 3, 3, 24, 'æ»≥Á«œººø‰~~ 251', 'π›∞©Ω¿¥œ¥Ÿ~~ 251', to_date('02/29/2024', 'MM/DD/RRRR'), 19, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (252, 4, 4, 25, 'æ»≥Á«œººø‰~~ 252', 'π›∞©Ω¿¥œ¥Ÿ~~ 252', to_date('02/28/2024', 'MM/DD/RRRR'), 21, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (253, 5, 1, 26, 'æ»≥Á«œººø‰~~ 253', 'π›∞©Ω¿¥œ¥Ÿ~~ 253', to_date('02/27/2024', 'MM/DD/RRRR'), 26, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (254, 6, 2, 27, 'æ»≥Á«œººø‰~~ 254', 'π›∞©Ω¿¥œ¥Ÿ~~ 254', to_date('02/26/2024', 'MM/DD/RRRR'), 2, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (255, 2, 3, 28, 'æ»≥Á«œººø‰~~ 255', 'π›∞©Ω¿¥œ¥Ÿ~~ 255', to_date('02/25/2024', 'MM/DD/RRRR'), 10, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (256, 3, 4, 29, 'æ»≥Á«œººø‰~~ 256', 'π›∞©Ω¿¥œ¥Ÿ~~ 256', to_date('02/24/2024', 'MM/DD/RRRR'), 3, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (257, 4, 1, 30, 'æ»≥Á«œººø‰~~ 257', 'π›∞©Ω¿¥œ¥Ÿ~~ 257', to_date('02/23/2024', 'MM/DD/RRRR'), 3, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (258, 5, 2, 31, 'æ»≥Á«œººø‰~~ 258', 'π›∞©Ω¿¥œ¥Ÿ~~ 258', to_date('02/22/2024', 'MM/DD/RRRR'), 16, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (259, 6, 3, 32, 'æ»≥Á«œººø‰~~ 259', 'π›∞©Ω¿¥œ¥Ÿ~~ 259', to_date('02/21/2024', 'MM/DD/RRRR'), 26, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (260, 7, 4, 33, 'æ»≥Á«œººø‰~~ 260', 'π›∞©Ω¿¥œ¥Ÿ~~ 260', to_date('02/20/2024', 'MM/DD/RRRR'), 22, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (261, 2, 1, 34, 'æ»≥Á«œººø‰~~ 261', 'π›∞©Ω¿¥œ¥Ÿ~~ 261', to_date('02/19/2024', 'MM/DD/RRRR'), 10, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (262, 3, 2, 35, 'æ»≥Á«œººø‰~~ 262', 'π›∞©Ω¿¥œ¥Ÿ~~ 262', to_date('02/18/2024', 'MM/DD/RRRR'), 30, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (263, 4, 3, 36, 'æ»≥Á«œººø‰~~ 263', 'π›∞©Ω¿¥œ¥Ÿ~~ 263', to_date('02/17/2024', 'MM/DD/RRRR'), 20, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (264, 5, 4, 37, 'æ»≥Á«œººø‰~~ 264', 'π›∞©Ω¿¥œ¥Ÿ~~ 264', to_date('02/16/2024', 'MM/DD/RRRR'), 1, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (265, 6, 1, 38, 'æ»≥Á«œººø‰~~ 265', 'π›∞©Ω¿¥œ¥Ÿ~~ 265', to_date('02/15/2024', 'MM/DD/RRRR'), 10, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (266, 7, 2, 39, 'æ»≥Á«œººø‰~~ 266', 'π›∞©Ω¿¥œ¥Ÿ~~ 266', to_date('02/14/2024', 'MM/DD/RRRR'), 23, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (267, 2, 3, 2, 'æ»≥Á«œººø‰~~ 267', 'π›∞©Ω¿¥œ¥Ÿ~~ 267', to_date('02/13/2024', 'MM/DD/RRRR'), 6, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (268, 3, 4, 3, 'æ»≥Á«œººø‰~~ 268', 'π›∞©Ω¿¥œ¥Ÿ~~ 268', to_date('02/12/2024', 'MM/DD/RRRR'), 9, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (269, 4, 1, 4, 'æ»≥Á«œººø‰~~ 269', 'π›∞©Ω¿¥œ¥Ÿ~~ 269', to_date('02/11/2024', 'MM/DD/RRRR'), 17, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (270, 5, 2, 5, 'æ»≥Á«œººø‰~~ 270', 'π›∞©Ω¿¥œ¥Ÿ~~ 270', to_date('02/10/2024', 'MM/DD/RRRR'), 24, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (271, 6, 3, 6, 'æ»≥Á«œººø‰~~ 271', 'π›∞©Ω¿¥œ¥Ÿ~~ 271', to_date('02/09/2024', 'MM/DD/RRRR'), 20, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (272, 7, 4, 7, 'æ»≥Á«œººø‰~~ 272', 'π›∞©Ω¿¥œ¥Ÿ~~ 272', to_date('02/08/2024', 'MM/DD/RRRR'), 28, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (273, 2, 1, 8, 'æ»≥Á«œººø‰~~ 273', 'π›∞©Ω¿¥œ¥Ÿ~~ 273', to_date('02/07/2024', 'MM/DD/RRRR'), 4, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (274, 3, 2, 9, 'æ»≥Á«œººø‰~~ 274', 'π›∞©Ω¿¥œ¥Ÿ~~ 274', to_date('02/06/2024', 'MM/DD/RRRR'), 23, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (275, 4, 3, 10, 'æ»≥Á«œººø‰~~ 275', 'π›∞©Ω¿¥œ¥Ÿ~~ 275', to_date('02/05/2024', 'MM/DD/RRRR'), 4, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (276, 5, 4, 11, 'æ»≥Á«œººø‰~~ 276', 'π›∞©Ω¿¥œ¥Ÿ~~ 276', to_date('02/04/2024', 'MM/DD/RRRR'), 6, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (277, 6, 1, 12, 'æ»≥Á«œººø‰~~ 277', 'π›∞©Ω¿¥œ¥Ÿ~~ 277', to_date('02/03/2024', 'MM/DD/RRRR'), 10, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (278, 2, 2, 13, 'æ»≥Á«œººø‰~~ 278', 'π›∞©Ω¿¥œ¥Ÿ~~ 278', to_date('02/02/2024', 'MM/DD/RRRR'), 12, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (279, 3, 3, 14, 'æ»≥Á«œººø‰~~ 279', 'π›∞©Ω¿¥œ¥Ÿ~~ 279', to_date('02/01/2024', 'MM/DD/RRRR'), 2, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (280, 4, 4, 15, 'æ»≥Á«œººø‰~~ 280', 'π›∞©Ω¿¥œ¥Ÿ~~ 280', to_date('01/31/2024', 'MM/DD/RRRR'), 10, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (281, 5, 1, 16, 'æ»≥Á«œººø‰~~ 281', 'π›∞©Ω¿¥œ¥Ÿ~~ 281', to_date('01/30/2024', 'MM/DD/RRRR'), 17, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (282, 6, 2, 17, 'æ»≥Á«œººø‰~~ 282', 'π›∞©Ω¿¥œ¥Ÿ~~ 282', to_date('01/29/2024', 'MM/DD/RRRR'), 15, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (283, 7, 3, 18, 'æ»≥Á«œººø‰~~ 283', 'π›∞©Ω¿¥œ¥Ÿ~~ 283', to_date('01/28/2024', 'MM/DD/RRRR'), 16, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (284, 2, 4, 19, 'æ»≥Á«œººø‰~~ 284', 'π›∞©Ω¿¥œ¥Ÿ~~ 284', to_date('01/27/2024', 'MM/DD/RRRR'), 4, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (285, 3, 1, 20, 'æ»≥Á«œººø‰~~ 285', 'π›∞©Ω¿¥œ¥Ÿ~~ 285', to_date('01/26/2024', 'MM/DD/RRRR'), 20, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (286, 4, 2, 21, 'æ»≥Á«œººø‰~~ 286', 'π›∞©Ω¿¥œ¥Ÿ~~ 286', to_date('01/25/2024', 'MM/DD/RRRR'), 30, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (287, 5, 3, 22, 'æ»≥Á«œººø‰~~ 287', 'π›∞©Ω¿¥œ¥Ÿ~~ 287', to_date('01/24/2024', 'MM/DD/RRRR'), 6, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (288, 6, 4, 23, 'æ»≥Á«œººø‰~~ 288', 'π›∞©Ω¿¥œ¥Ÿ~~ 288', to_date('01/23/2024', 'MM/DD/RRRR'), 30, 4, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (289, 7, 1, 24, 'æ»≥Á«œººø‰~~ 289', 'π›∞©Ω¿¥œ¥Ÿ~~ 289', to_date('01/22/2024', 'MM/DD/RRRR'), 4, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (290, 2, 2, 25, 'æ»≥Á«œººø‰~~ 290', 'π›∞©Ω¿¥œ¥Ÿ~~ 290', to_date('01/21/2024', 'MM/DD/RRRR'), 30, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (291, 3, 3, 26, 'æ»≥Á«œººø‰~~ 291', 'π›∞©Ω¿¥œ¥Ÿ~~ 291', to_date('01/20/2024', 'MM/DD/RRRR'), 7, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (292, 4, 4, 27, 'æ»≥Á«œººø‰~~ 292', 'π›∞©Ω¿¥œ¥Ÿ~~ 292', to_date('01/19/2024', 'MM/DD/RRRR'), 22, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (293, 5, 1, 28, 'æ»≥Á«œººø‰~~ 293', 'π›∞©Ω¿¥œ¥Ÿ~~ 293', to_date('01/18/2024', 'MM/DD/RRRR'), 18, 6, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (294, 6, 2, 29, 'æ»≥Á«œººø‰~~ 294', 'π›∞©Ω¿¥œ¥Ÿ~~ 294', to_date('01/17/2024', 'MM/DD/RRRR'), 13, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (295, 7, 3, 30, 'æ»≥Á«œººø‰~~ 295', 'π›∞©Ω¿¥œ¥Ÿ~~ 295', to_date('01/16/2024', 'MM/DD/RRRR'), 14, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (296, 2, 4, 31, 'æ»≥Á«œººø‰~~ 296', 'π›∞©Ω¿¥œ¥Ÿ~~ 296', to_date('01/15/2024', 'MM/DD/RRRR'), 30, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (297, 3, 1, 32, 'æ»≥Á«œººø‰~~ 297', 'π›∞©Ω¿¥œ¥Ÿ~~ 297', to_date('01/14/2024', 'MM/DD/RRRR'), 17, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (298, 4, 2, 33, 'æ»≥Á«œººø‰~~ 298', 'π›∞©Ω¿¥œ¥Ÿ~~ 298', to_date('01/13/2024', 'MM/DD/RRRR'), 12, 2, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (299, 5, 3, 34, 'æ»≥Á«œººø‰~~ 299', 'π›∞©Ω¿¥œ¥Ÿ~~ 299', to_date('01/12/2024', 'MM/DD/RRRR'), 10, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (300, 6, 4, 35, 'æ»≥Á«œººø‰~~ 300', 'π›∞©Ω¿¥œ¥Ÿ~~ 300', to_date('01/11/2024', 'MM/DD/RRRR'), 15, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (301, 2, 1, 36, 'æ»≥Á«œººø‰~~ 301', 'π›∞©Ω¿¥œ¥Ÿ~~ 301', to_date('01/10/2024', 'MM/DD/RRRR'), 21, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (302, 3, 2, 37, 'æ»≥Á«œººø‰~~ 302', 'π›∞©Ω¿¥œ¥Ÿ~~ 302', to_date('01/09/2024', 'MM/DD/RRRR'), 20, 10, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (303, 4, 3, 38, 'æ»≥Á«œººø‰~~ 303', 'π›∞©Ω¿¥œ¥Ÿ~~ 303', to_date('01/08/2024', 'MM/DD/RRRR'), 13, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (304, 5, 4, 39, 'æ»≥Á«œººø‰~~ 304', 'π›∞©Ω¿¥œ¥Ÿ~~ 304', to_date('01/07/2024', 'MM/DD/RRRR'), 22, 1, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (305, 6, 1, 2, 'æ»≥Á«œººø‰~~ 305', 'π›∞©Ω¿¥œ¥Ÿ~~ 305', to_date('01/06/2024', 'MM/DD/RRRR'), 19, 8, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (306, 7, 2, 3, 'æ»≥Á«œººø‰~~ 306', 'π›∞©Ω¿¥œ¥Ÿ~~ 306', to_date('01/05/2024', 'MM/DD/RRRR'), 23, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (307, 2, 3, 4, 'æ»≥Á«œººø‰~~ 307', 'π›∞©Ω¿¥œ¥Ÿ~~ 307', to_date('01/04/2024', 'MM/DD/RRRR'), 6, 3, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (308, 3, 4, 5, 'æ»≥Á«œººø‰~~ 308', 'π›∞©Ω¿¥œ¥Ÿ~~ 308', to_date('01/03/2024', 'MM/DD/RRRR'), 10, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (309, 4, 1, 6, 'æ»≥Á«œººø‰~~ 309', 'π›∞©Ω¿¥œ¥Ÿ~~ 309', to_date('01/02/2024', 'MM/DD/RRRR'), 21, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (310, 5, 2, 7, 'æ»≥Á«œººø‰~~ 310', 'π›∞©Ω¿¥œ¥Ÿ~~ 310', to_date('01/01/2024', 'MM/DD/RRRR'), 16, 7, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (311, 6, 3, 8, 'æ»≥Á«œººø‰~~ 311', 'π›∞©Ω¿¥œ¥Ÿ~~ 311', to_date('12/31/2023', 'MM/DD/RRRR'), 30, 0, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (312, 7, 4, 9, 'æ»≥Á«œººø‰~~ 312', 'π›∞©Ω¿¥œ¥Ÿ~~ 312', to_date('12/30/2023', 'MM/DD/RRRR'), 4, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (313, 2, 1, 10, 'æ»≥Á«œººø‰~~ 313', 'π›∞©Ω¿¥œ¥Ÿ~~ 313', to_date('12/29/2023', 'MM/DD/RRRR'), 29, 9, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (314, 3, 2, 11, 'æ»≥Á«œººø‰~~ 314', 'π›∞©Ω¿¥œ¥Ÿ~~ 314', to_date('12/28/2023', 'MM/DD/RRRR'), 22, 5, 'Y', 0);

INSERT INTO BOARD (BOARD_NO, TAB_NO, LICENSE_NO, MEMBER_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, LIKE_COUNT, HATE_COUNT, STATUS, VIEW_COUNT) 
VALUES (315, 4, 3, 12, 'æ»≥Á«œººø‰~~ 315', 'π›∞©Ω¿¥œ¥Ÿ~~ 315', to_date('12/27/2023', 'MM/DD/RRRR'), 7, 8, 'Y', 0);

COMMIT;
